import localFont from "next/font/local";
import "./globals.css";

const dmSans = localFont({
  src: "./fonts/DMSans.ttf",
  variable: "--font-dm-sans",
  weight: "100 900",
});
const ribeye = localFont({
  src: "./fonts/Ribeye-Regular.ttf",
  variable: "--font-ribeye",
  weight: "100 900",
});

export const metadata = {
  title: "Lumber",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body className={`${dmSans.variable} ${ribeye.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
